### ISSUE TITLE
Python 3.10 compatibility

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/terraingen#15]
`offline_gen.py` fails when run under Python 3.10.8. Initial googling leads me to believe it's related to [PEP-353](https://peps.python.org/pep-0353/)

``` python
[wickedshell@lackey terraingen]$ python --version
Python 3.10.8
[wickedshell@lackey terraingen]$ python offline_gen.py 
Storing in /home/wickedshell/code/terraingen/processedTerrain
Creating for -59 -180
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Creating for -60 -180
Creating for -61 -180
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Creating for -57 -180
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Creating for -56 -180
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Creating for -58 -180
Creating for -54 -180
Creating for -55 -180
Creating for -53 -180
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Creating for -50 -180
Creating for -51 -180
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Creating for -52 -180
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Creating for -48 -180
Creating for -49 -180
Creating for -47 -180
Worker exception: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Creating for -45 -180
Creating for -46 -180
Traceback (most recent call last):
  File "/home/wickedshell/code/terraingen/offline_gen.py", line 135, in <module>
    result.get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/wickedshell/code/terraingen/offline_gen.py", line 26, in worker
    if not create_degree(downloader, lat, long, targetFolder, spacing, format):
  File "/home/wickedshell/code/terraingen/terrain_gen.py", line 323, in create_degree
    dfile.write(grid)
  File "/home/wickedshell/code/terraingen/terrain_gen.py", line 249, in write
    block.crc = crc16.crc16xmodem(buf[:IO_BLOCK_DATA_SIZE])
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
[wickedshell@lackey terraingen]$ git reflog
ce56f6d (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: clone: from https://github.com/ArduPilot/terraingen.git
```

**Comment by tridge** [comment]
This issue was fixed in commit 128f926 which switched from the `crc16` library to `fastcrc`. The `fastcrc` library is compatible with Python 3.10+.

The fix is already on master. Please update to the latest version and run `pip install -r requirements.txt` to install `fastcrc`.
